### ISSUE TITLE
Iso 0.4 missing in ALPHA

### ISSUE THREAD

**Issue by andresti** [cms-hh-pd/alp_analysis#52]
/lustre/cmswork/atiko/Hbb/mixing/CMSSW_8_0_25/src/Analysis/alp_analysis/interface/IsoMuFilterOperator.h:28:28: error: no member named 'iso04' in 'alp::Lepton'
             return ( muon.iso04() > iso04_max_  || muon.pt() < pt_min_ ) ; });

Only iso03 in here: https://github.com/CMS-PD/ALPHA/blob/master/interface/alp_objects.h

**Comment by MDallOsso** [comment]
Yes, I think it is related to a commit that I made, partially.  Check out the alpha folder in my lustre area. ...hh2016/CMSSW_8_25/src...Sorry, Martino


Inviato dal mio dispositivo Samsung

-------- Messaggio originale --------
Da: andresti <notifications@github.com> 
Data: 08/08/17  16:43  (GMT+01:00) 
A: cms-hh-pd/alp_analysis <alp_analysis@noreply.github.com> 
Cc: Subscribed <subscribed@noreply.github.com> 
Oggetto: [cms-hh-pd/alp_analysis] Iso 0.4 missing in ALPHA (#52) 

/lustre/cmswork/atiko/Hbb/mixing/CMSSW_8_0_25/src/Analysis/alp_analysis/interface/IsoMuFilterOperator.h:28:28: error: no member named 'iso04' in 'alp::Lepton'

return ( muon.iso04() > iso04_max_  || muon.pt() < pt_min_ ) ; });
Only iso03 in here: https://github.com/CMS-PD/ALPHA/blob/master/interface/alp_objects.h

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cms-hh-pd/alp_analysis","title":"cms-hh-pd/alp_analysis","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cms-hh-pd/alp_analysis"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Iso 0.4 missing in ALPHA (#52)"}],"action":{"name":"View Issue","url":"https://github.com/cms-hh-pd/alp_analysis/issues/52"}}}

**Comment by MDallOsso** [comment]
solved with https://github.com/CMS-PD/ALPHA/commit/aab024bebaecfcf05d0a86283b1d2117378f42d8
